### ISSUE TITLE
The picture are not well positioned. We can't see all of the face. 

### ISSUE THREAD

**Issue by caroliner** [Asche42/provocare#9]

**Comment by thomascharbonnel** [comment]
This is the way it was coded by [JuniorISEP](http://www.juniorisep.com/).

**Comment by thomascharbonnel** [comment]
For reference, excerpt from `app/assets/stylesheets/corps.css`:

``` css
.photo_case{
        height: 100%;
        width: 50%;
        overflow: hidden;
        display: flex;
        /*border:1px solid;*/
}
```
